package de.kortty.core;

/**
 * Supported AI actions for terminal selections.
 */
public enum AiAction {
    SUMMARIZE,
    SOLVE_PROBLEM,
    ASK,
    GENERATE_CHAT_TITLE,
    GENERATE_SNIPPET_METADATA,
    CORRECT_SNIPPET_DESCRIPTION,
    CORRECT_SNIPPET_SELECTION_TEXT,
    TRANSLATE_SNIPPET_SELECTION_TEXT,
    DESCRIBE_SNIPPET_SELECTION,
    DESCRIBE_SNIPPET_FULL,
    GENERATE_SNIPPET_ALTERNATIVES,
    COMPLETE_SNIPPET_CODE,
    REVIEW_SNIPPET_CODE,
    IMPROVE_SNIPPET_CODE,
    SECURITY_REVIEW_SNIPPET_CODE,
    APPLY_SNIPPET_SECURITY_FIXES,
    GENERATE_SNIPPET_PLANTUML
}
