package de.kortty.core;

import com.google.gson.Gson;
import org.testng.annotations.Test;

import java.util.List;
import java.util.Map;

import static com.google.common.truth.Truth.assertThat;

/** Regression contracts for the analysis request shape, fallback diagrams and analysis/apply language routing. */
class SnippetAiAnalysisContractTest {

    private static final Gson GSON = new Gson();

    private static final String CONDITIONAL_BASH = """
        BACKUP_DIR=/srv/backups
        if tar -czf "$BACKUP_DIR/archive.tgz" /srv/data; then
          echo "Backup complete"
        else
          echo "Backup failed" >&2
          exit 1
        fi
        """;

    @Test
    void analysisRequestNoLongerAsksForAnyMermaidPayload() throws Exception {
        CapturingAiService aiService = new CapturingAiService(GSON.toJson(Map.of(
            "summary", "Erstellt ein Archiv und behandelt Erfolg und Fehler getrennt.",
            "dependencies", List.of(),
            "improvements", List.of())));

        SnippetAiResponseSupport.ScriptAnalysis result = SnippetAiWorkflowSupport.analyzeSnippetCode(
            aiService, null, CONDITIONAL_BASH, "bash", null, "de", null);

        assertThat(result.isUsable()).isTrue();
        assertThat(aiService.executionCount).isEqualTo(1);
        AiRequest request = aiService.lastRequest;
        String completePrompt = AiPromptBuilder.buildSystemPrompt(request) + "\n"
            + AiPromptBuilder.buildUserPrompt(request);
        // The diagram is generated by a separate GENERATE_SNIPPET_MERMAID request; the analysis
        // request must not dilute the model's attention with any Mermaid instructions.
        assertThat(completePrompt).doesNotContain("mermaid");
        assertThat(completePrompt).doesNotContain("Mermaid");
        assertThat(completePrompt).doesNotContain("codeReferences");
        assertThat(completePrompt).doesNotContain("flowchart TD");
        assertThat(completePrompt).doesNotContain("Diagram label language");
    }

    @Test
    void conditionalLocalFallbackContainsExplicitSuccessAndFailureBranches() {
        String fallback = SnippetDiagramSupport.buildFallbackLogicalStructureMermaid(CONDITIONAL_BASH, "bash");

        assertThat(SnippetDiagramSupport.validateMermaid(fallback).valid()).isTrue();
        assertThat(fallback).contains("decision_1{\"Main command succeeds?\"}");
        assertThat(fallback).contains("decision_1 -->|yes| success_1");
        assertThat(fallback).contains("decision_1 -->|no| failure_1");
        assertThat(fallback).contains("success_1 --> stop_1");
        assertThat(fallback).contains("failure_1 --> stop_1");
        assertThat(fallback).doesNotContain("work_1 --> stop_1");
    }

    @Test
    void analysisRequestUsesGuiLanguageForReportAndCodeLanguageForSnippet() throws Exception {
        CapturingAiService aiService = new CapturingAiService("""
            {
              "summary": "Prüft einen Statuscode.",
              "dependencies": [],
              "improvements": []
            }
            """);

        SnippetAiWorkflowSupport.analyzeSnippetCode(
            aiService, null, "if status_ok():\n    print('ok')", "python", null, "de", null);

        AiRequest request = aiService.lastRequest;
        assertThat(request.action()).isEqualTo(AiAction.ANALYZE_SNIPPET_CODE);
        assertThat(request.responseLanguageCode()).isEqualTo("de");
        assertThat(request.conversationContext()).contains("Snippet language: python");
        assertThat(request.conversationContext()).contains("Natural language for the analysis: de");
        assertThat(AiPromptBuilder.buildSystemPrompt(request))
            .contains("Write human-readable text in language code de");
    }

    @Test
    void applySelectedKeepsBashCodeLanguageSeparateFromGuiLanguage() throws Exception {
        String originalSnippet = "#!/usr/bin/env bash\nprintf '%s\\n' $value";
        CapturingAiService aiService = new CapturingAiService(GSON.toJson(Map.of(
            "replacement", "#!/usr/bin/env bash\n# Eingabe sicher prüfen\nprintf '%s\\n' \"$value\"",
            "summary", "Die Eingabe wird sicher verarbeitet.",
            "changes", List.of(Map.of(
                "finding", "SEC-1",
                "anchor", "printf '%s\\n' \"$value\"",
                "reason", "Verhindert Wortaufteilung.")))));
        List<SnippetAiResponseSupport.ScriptImprovement> selectedImprovements = List.of(
            new SnippetAiResponseSupport.ScriptImprovement(
                "SEC-1", "security", "high", "Variable quoten", "Die Variable ist ungequotet.",
                "Die Expansion in doppelte Anführungszeichen setzen.", 2));
        List<SnippetAiResponseSupport.ScriptDependency> selectedDependencies = List.of(
            new SnippetAiResponseSupport.ScriptDependency(
                "D1", "printf", "program", "Ausgabe erzeugen", "Shell-Builtin bevorzugen"));

        SnippetAiResponseSupport.SnippetSecurityFix result = SnippetAiWorkflowSupport.applySnippetImprovements(
            aiService,
            null,
            originalSnippet,
            "bash",
            null,
            "de",
            selectedImprovements,
            selectedDependencies,
            null);

        AiRequest request = aiService.lastRequest;
        assertThat(result.isUsable()).isTrue();
        assertThat(request.action()).isEqualTo(AiAction.APPLY_SNIPPET_IMPROVEMENTS);
        assertThat(request.responseLanguageCode()).isEqualTo("de");
        assertThat(request.conversationContext()).contains("Snippet language: bash");
        assertThat(request.conversationContext()).contains("Natural language for the summary: de");
        assertThat(request.conversationContext()).contains("SEC-1 [security/high] Variable quoten");
        assertThat(request.conversationContext()).contains("D1 [dependency] printf");
        assertThat(request.conversationContext()).doesNotContain(originalSnippet);
        String userPrompt = AiPromptBuilder.buildUserPrompt(request);
        assertThat(userPrompt).contains("Full script content to update");
        assertThat(userPrompt).doesNotContain("Selected terminal text");
        assertThat(userPrompt.indexOf(originalSnippet)).isEqualTo(userPrompt.lastIndexOf(originalSnippet));
        assertThat(AiPromptBuilder.buildSystemPrompt(request))
            .contains("comments or user-facing strings in language code de");
    }

    private static final class CapturingAiService implements AiService {
        private final String response;
        private AiRequest lastRequest;
        private int executionCount;

        private CapturingAiService(String response) {
            this.response = response;
        }

        @Override
        public AiExecutionResult execute(AiRequest request) {
            lastRequest = request;
            executionCount++;
            return new AiExecutionResult(response, null);
        }

        @Override
        public boolean testConnection() {
            return true;
        }
    }
}
