Args = --no-fallback \
       --enable-url-protocols=https,http \
       --initialize-at-run-time=org.apache.sshd \
       --initialize-at-run-time=ch.qos.logback \
       --initialize-at-run-time=org.slf4j \
       -H:+ReportExceptionStackTraces
